version: "3"

# https://github.com/near/docs/blob/975642ad49338bf8728a675def1f8bec8a780922/docs/local-setup/entire-setup.md
# https://github.com/kurtosis-tech/near-kurtosis-module/tree/develop/kurtosis-module/impl/services

services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: localnear
      POSTGRES_PASSWORD: localnear
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localnear"]
      interval: 5s
      timeout: 5s
      retries: 5
  indexer:
    build:
      context: ./indexer
    volumes:
      - ./.near:/root/.near
    environment:
      DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/status"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "13031:3030"
      - "34567:24567"
  analytics:
    image: nguquen/near-analytics:latest
    environment:
      ANALYTICS_DATABASE_URL: postgres://localnear:localnear@postgres/analytics
      INDEXER_DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    depends_on:
      indexer:
        condition: service_healthy
  explorer-wamp:
    image: kurtosistech/near-explorer_wamp:latest
    environment:
      WAMP_NEAR_EXPLORER_PORT: 8080
      WAMP_NEAR_EXPLORER_BACKEND_SECRET: back
    ports:
      - "18080:8080"
    depends_on:
      indexer:
        condition: service_healthy
  explorer-backend:
    image: kurtosistech/near-explorer_backend:5ef5b6c
    environment:
      NEAR_READ_ONLY_INDEXER_DATABASE_USERNAME: "localnear"
      NEAR_READ_ONLY_INDEXER_DATABASE_PASSWORD: "localnear"
      NEAR_READ_ONLY_INDEXER_DATABASE_HOST: "postgres"
      NEAR_READ_ONLY_INDEXER_DATABASE_NAME: "indexer"
      NEAR_READ_ONLY_ANALYTICS_DATABASE_USERNAME: "localnear"
      NEAR_READ_ONLY_ANALYTICS_DATABASE_PASSWORD: "localnear"
      NEAR_READ_ONLY_ANALYTICS_DATABASE_HOST: "postgres"
      NEAR_READ_ONLY_ANALYTICS_DATABASE_NAME: "analytics"
      NEAR_READ_ONLY_TELEMETRY_DATABASE_USERNAME: "localnear"
      NEAR_READ_ONLY_TELEMETRY_DATABASE_PASSWORD: "localnear"
      NEAR_READ_ONLY_TELEMETRY_DATABASE_HOST: "postgres"
      NEAR_READ_ONLY_TELEMETRY_DATABASE_NAME: "telemetry"
      NEAR_WRITE_ONLY_TELEMETRY_DATABASE_USERNAME: "localnear"
      NEAR_WRITE_ONLY_TELEMETRY_DATABASE_PASSWORD: "localnear"
      NEAR_WRITE_ONLY_TELEMETRY_DATABASE_HOST: "postgres"
      NEAR_WRITE_ONLY_TELEMETRY_DATABASE_NAME: "telemetry"
      WAMP_NEAR_EXPLORER_URL: "ws://explorer-wamp:8080/ws"
      WAMP_NEAR_EXPLORER_BACKEND_SECRET: "back"
      WAMP_NEAR_NETWORK_NAME: "localnet"
      NEAR_IS_LEGACY_SYNC_BACKEND_ENABLED: "false"
      NEAR_IS_INDEXER_BACKEND_ENABLED: "true"
      NEAR_RPC_URL: "http://indexer:3030"
    depends_on:
      indexer:
        condition: service_healthy
  explorer-frontend:
    image: kurtosistech/near-explorer_frontend:5ef5b6c
    environment:
      WAMP_NEAR_EXPLORER_INTERNAL_URL: "ws://explorer-wamp:8080/ws"
      WAMP_NEAR_EXPLORER_URL: "ws://127.0.0.1:18080/ws"
      NEAR_EXPLORER_DATA_SOURCE: "INDEXER_BACKEND"
      PORT: 3032
      NEAR_NETWORKS: "[{\"name\": \"localnet\", \"explorerLink\": \"http://localhost:13032/\", \"aliases\": [\"localhost:13032\", \"127.0.0.1:13032\"], \"nearWalletProfilePrefix\": \"https://wallet.testnet.near.org/profile\"}]"
    ports:
      - "13032:3032"
  contract-helper:
    build:
      context: ./contract-helper
    environment:
      MAIL_HOST: "smtp.ethereal.email"
      MAIL_PASSWORD: ""
      MAIL_PORT: "587"
      MAIL_USER: ""
      NEW_ACCOUNT_AMOUNT: "100000000000000000000000000"
      NODE_ENV: "development"
      NEAR_WALLET_ENV: "development"
      PORT: 3033
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_FROM_PHONE: "+14086179592"
      WALLET_URL: ""
      INDEXER_DB_CONNECTION: "postgres://localnear:localnear@postgres/indexer"
      NODE_URL: "http://indexer:3030"
    depends_on:
      indexer:
        condition: service_healthy
    volumes:
      - ./.near:/root/.near:ro
    ports:
      - "13033:3033"
  wallet:
    build:
      context: ./wallet
      args:
        - ACCESS_KEY_FUNDING_AMOUNT=3000000000000000000000000
        - ACCOUNT_ID_SUFFIX=test.near
        - NETWORK_ID=localnet
        - IS_MAINNET=false
        - NODE_URL=http://127.0.0.1:13031
        - EXPLORER_URL=http://127.0.0.1:13032
        - ACCOUNT_HELPER_URL=http://127.0.0.1:13033
    depends_on:
      indexer:
        condition: service_healthy
    ports:
      - "13034:3004"
volumes:
  postgres: ~
