version: "3"

# https://github.com/near/docs/blob/975642ad49338bf8728a675def1f8bec8a780922/docs/local-setup/entire-setup.md
# https://github.com/kurtosis-tech/near-kurtosis-module/

services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: localnear
      POSTGRES_PASSWORD: localnear
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localnear"]
      interval: 5s
      timeout: 5s
      retries: 5
  indexer:
    build:
      context: ./indexer
    volumes:
      - ./.near:/root/.near
    environment:
      DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/status"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "13031:3030"
      - "34567:24567"
  analytics:
    image: nguquen/near-analytics:latest
    environment:
      ANALYTICS_DATABASE_URL: postgres://localnear:localnear@postgres/analytics
      INDEXER_DATABASE_URL: postgres://localnear:localnear@postgres/indexer
    depends_on:
      indexer:
        condition: service_healthy
  explorer-backend:
    image: nguquen/near-explorer-backend:latest
    environment:
      NEAR_EXPLORER_CONFIG__NETWORK_NAME: localnet
      NEAR_EXPLORER_CONFIG__ARCHIVAL_RPC_URL: "http://indexer:3030"
      NEAR_EXPLORER_CONFIG__PORT: 8080

      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_INDEXER__HOST: postgres
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_INDEXER__DATABASE: indexer
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_INDEXER__USER: localnear
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_INDEXER__PASSWORD: localnear

      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_ANALYTICS__HOST: postgres
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_ANALYTICS__DATABASE: analytics
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_ANALYTICS__USER: localnear
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_ANALYTICS__PASSWORD: localnear

      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_TELEMETRY__HOST: postgres
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_TELEMETRY__DATABASE: telemetry
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_TELEMETRY__USER: localnear
      NEAR_EXPLORER_CONFIG__DB__READ_ONLY_TELEMETRY__PASSWORD: localnear

      NEAR_EXPLORER_CONFIG__DB__WRITE_ONLY_TELEMETRY__HOST: postgres
      NEAR_EXPLORER_CONFIG__DB__WRITE_ONLY_TELEMETRY__DATABASE: telemetry
      NEAR_EXPLORER_CONFIG__DB__WRITE_ONLY_TELEMETRY__USER: localnear
      NEAR_EXPLORER_CONFIG__DB__WRITE_ONLY_TELEMETRY__PASSWORD: localnear
    ports:
      - "18080:8080"
    depends_on:
      indexer:
        condition: service_healthy
  explorer-frontend:
    image: nguquen/near-explorer-frontend:latest
    environment:
      NEAR_EXPLORER_CONFIG__NETWORK_NAME: "localnet"
      NEAR_EXPLORER_CONFIG__NETWORKS: "{\"localnet\":{\"explorerLink\":\"http://localhost:13032/\",\"nearWalletProfilePrefix\":\"http://localhost:13034/profile\"}}"
      PORT: 3032
      NEAR_EXPLORER_CONFIG__BACKEND_SSR__HOSTS__LOCALNET: explorer-backend
      NEAR_EXPLORER_CONFIG__BACKEND_SSR__PORT: 8080
      NEAR_EXPLORER_CONFIG__BACKEND_SSR__SECURE: "false"
      NEAR_EXPLORER_CONFIG__BACKEND__HOSTS__LOCALNET: localhost
      NEAR_EXPLORER_CONFIG__BACKEND__PORT: 18080
      NEAR_EXPLORER_CONFIG__BACKEND__SECURE: "false"
    ports:
      - "13032:3032"
  contract-helper:
    build:
      context: ./contract-helper
    environment:
      START_TYPE: "start"
      MAIL_HOST: "smtp.ethereal.email"
      MAIL_PASSWORD: ""
      MAIL_PORT: "587"
      MAIL_USER: ""
      NEW_ACCOUNT_AMOUNT: "100000000000000000000000000"
      NODE_ENV: "development"
      NEAR_WALLET_ENV: "testnet"
      PORT: 3033
      TWILIO_ACCOUNT_SID: "ACdummy"
      TWILIO_AUTH_TOKEN: "dummy"
      TWILIO_FROM_PHONE: "+14086179592"
      WALLET_URL: ""
      INDEXER_DB_CONNECTION: "postgres://localnear:localnear@postgres/indexer"
      NODE_URL: "http://indexer:3030"
    depends_on:
      indexer:
        condition: service_healthy
    volumes:
      - ./.near:/root/.near:ro
    ports:
      - "13033:3033"
  contract-helper-indexer:
    build:
      context: ./contract-helper
    environment:
      START_TYPE: "start:indexer"
      NODE_ENV: "development"
      NEAR_WALLET_ENV: "testnet"
      PORT: 3033
      INDEXER_DB_REPLICAS: '["postgres://localnear:localnear@postgres/indexer"]'
    depends_on:
      indexer:
        condition: service_healthy
    volumes:
      - ./.near:/root/.near:ro
    ports:
      - "23033:3033"
  wallet:
    build:
      context: ./wallet
      args:
        - ACCESS_KEY_FUNDING_AMOUNT=3000000000000000000000000
        - ACCOUNT_ID_SUFFIX=test.near
        - NETWORK_ID=localnet
        - IS_MAINNET=false
        - NODE_URL=http://127.0.0.1:13031
        - EXPLORER_URL=http://127.0.0.1:13032
        - ACCOUNT_HELPER_URL=http://127.0.0.1:13033
        - INDEXER_SERVICE_URL=http://127.0.0.1:23033
    depends_on:
      indexer:
        condition: service_healthy
    ports:
      - "13034:3004"
volumes:
  postgres: ~
